export const sectors = [
  'Automotive',
  'Baby Products',
  'Beauty',
  'Books',
  'Camera and Accessories',
  'Clothing and Accessories',
  'Computer_and_Accessories',
  'Consumer Electronics',
  'Cleaning and Hygiene products',
  'Disinfectant Wipes and Sprays',
  'Everything Else',
  'Face Masks (N95, KN95)',
  'Face Masks (Other)',
  'Fine Art',
  'Furniture',
  'Gift Card',
  'Grocery and Gourmet Food',
  'Handbags',
  'Hand Sanitisers',
  'Health and Personal Care',
  'Home and Garden',
  'Household Staples',
  'Industrial and Scientific Supply',
  'Jewellery',
  'Kindle Accessories',
  'Kitchen',
  'Luggage and Travel Accessories',
  'Mobile and Accessories',
  'Movies and DVD',
  'Music',
  'Musical Instruments',
  'Office Products',
  'Packaged Food',
  'Pet Supplies',
  'Shoes',
  'Software',
  'Sports and Outdoors',
  'Sunglasses and Eyewear',
  'Tools and Home Improvement',
  'Toys and Games',
  'Video Games',
  'Watches',
];
export const objForm = {
  description: 'assddffgggg',
  discountPrice: 80,
  marketPrice: 90,
  name: 'Milk',
  address: '27/9 kalyan puri near jain milan',
  category: 'Everything Else',
  city: 'Merrut',
  country: 'India',
  gstIn: 'Ridam',
  pinCode: 251001,
  state: 'Uttar Pradesh',
  storeName: 'Garg Traders',
};
