const data = [
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16touch-silver-select-201911?wid=1808&hei=1686&fmt=jpeg&qlt=80&.v=1572825196932',
    title: 'Macbook',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 1,00,000',
    discount: '90% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343703000',
    title: 'iPhone',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 60,000',
    discount: '70% off',
  },
  {
    src: 'https://assets.ajio.com/medias/sys_master/root/h15/h40/15378508415006/-473Wx593H-410242907-3st-MODEL.jpg',
    title: 'T-Shirt',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 500',
    discount: '50% off',
  },
  {
    src: 'https://www.ulcdn.net/images/products/295663/slide/1998x1089/Agatha_Table_1.jpg?1590637821',
    title: 'Table',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 3200',
    discount: '35% off',
  },
  {
    src: 'https://images.firstpost.com/fpimages/1200x800/fixed/jpg/2020/06/boat-airdopes-1280.jpg',
    title: 'Boat Airdopes 441',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 2000',
    discount: '25% off',
  },
  {
    src: 'https://assets.ajio.com/medias/sys_master/root/h15/h40/15378508415006/-473Wx593H-410242907-3st-MODEL.jpg',
    title: 'T-Shirt',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 500',
    discount: '50% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16touch-silver-select-201911?wid=1808&hei=1686&fmt=jpeg&qlt=80&.v=1572825196932',
    title: 'Macbook',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 1,00,000',
    discount: '90% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16touch-silver-select-201911?wid=1808&hei=1686&fmt=jpeg&qlt=80&.v=1572825196932',
    title: 'Macbook',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 1,00,000',
    discount: '90% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343703000',
    title: 'iPhone',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 60,000',
    discount: '70% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343703000',
    title: 'iPhone',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 60,000',
    discount: '70% off',
  },
  {
    src: 'https://assets.ajio.com/medias/sys_master/root/h15/h40/15378508415006/-473Wx593H-410242907-3st-MODEL.jpg',
    title: 'T-Shirt',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 500',
    discount: '50% off',
  },
  {
    src: 'https://www.ulcdn.net/images/products/295663/slide/1998x1089/Agatha_Table_1.jpg?1590637821',
    title: 'Table',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 3200',
    discount: '35% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343703000',
    title: 'iPhone',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 60,000',
    discount: '70% off',
  },
  {
    src: 'https://assets.ajio.com/medias/sys_master/root/h15/h40/15378508415006/-473Wx593H-410242907-3st-MODEL.jpg',
    title: 'T-Shirt',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 500',
    discount: '50% off',
  },
  {
    src: 'https://www.ulcdn.net/images/products/295663/slide/1998x1089/Agatha_Table_1.jpg?1590637821',
    title: 'Table',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 3200',
    discount: '35% off',
  },
  {
    src: 'https://www.ulcdn.net/images/products/295663/slide/1998x1089/Agatha_Table_1.jpg?1590637821',
    title: 'Table',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 3200',
    discount: '35% off',
  },
  {
    src: 'https://kbimages1-a.akamaihd.net/aad58714-db6b-45be-acbb-cc1b57bc8a84/1200/1200/False/angels-demons-1.jpg',
    title: 'Angels and Demons',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 350',
    discount: '80% off',
  },
  {
    src: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-red-select-2020?wid=940&hei=1112&fmt=png-alpha&.v=1604343703000',
    title: 'iPhone',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 60,000',
    discount: '70% off',
  },
  {
    src: 'https://assets.ajio.com/medias/sys_master/root/h15/h40/15378508415006/-473Wx593H-410242907-3st-MODEL.jpg',
    title: 'T-Shirt',
    info: 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups',
    price: '₹ 500',
    discount: '50% off',
  },
];

export default data;
